//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandcastle.HelpRegister.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandcastle.HelpRegister.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate the file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorCannotValidateXmlFile {
            get {
                return ResourceManager.GetString("ErrorCannotValidateXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given command-line parameter &quot;{0}&quot; is not valid..
        /// </summary>
        internal static string ErrorInvalidCommandLine {
            get {
                return ResourceManager.GetString("ErrorInvalidCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need Administrator or Power user privileges to run this application..
        /// </summary>
        internal static string ErrorInvalidPrivileges {
            get {
                return ResourceManager.GetString("ErrorInvalidPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ErrorInvalidXmlFile {
            get {
                return ResourceManager.GetString("ErrorInvalidXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Help 2.0 Environment is not installed..
        /// </summary>
        internal static string ErrorNoHelp2Environment {
            get {
                return ResourceManager.GetString("ErrorNoHelp2Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging namespace &quot;{0}&quot; to reflect the changes, please wait....
        /// </summary>
        internal static string MergeHelpNamespace {
            get {
                return ResourceManager.GetString("MergeHelpNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering help document &quot;{0}&quot;.
        /// </summary>
        internal static string RegisterHelpDocument {
            get {
                return ResourceManager.GetString("RegisterHelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering filter &quot;{0}&quot;.
        /// </summary>
        internal static string RegisterHelpFilter {
            get {
                return ResourceManager.GetString("RegisterHelpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering namespace &quot;{0}&quot;.
        /// </summary>
        internal static string RegisterHelpNamespace {
            get {
                return ResourceManager.GetString("RegisterHelpNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering &quot;{0}&quot; as plug-in for &quot;{1}&quot;.
        /// </summary>
        internal static string RegisterHelpPlugin {
            get {
                return ResourceManager.GetString("RegisterHelpPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:   {0} Command [Option] Filename
        ///
        ///Commands:
        ///    /r           Register help documents, filters and plug-ins
        ///    /u          Unregister all.
        ///    +r         Register help document and filters.
        ///    -r           Unregister help documents and filters.
        ///    +p         Register plug-ins.
        ///    -p           Unregister plug-ins.
        ///    /? or -?  Show this help page or dialog.
        ///    /v or -v  Open the registered help file for viewing.
        ///
        ///Options:
        ///    /quiet                Suppress all messages.
        ///    /nologo   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegisterToolCommandLineOptions {
            get {
                return ResourceManager.GetString("RegisterToolCommandLineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing help document &quot;{0}&quot;.
        /// </summary>
        internal static string RemoveHelpDocument {
            get {
                return ResourceManager.GetString("RemoveHelpDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing filter &quot;{0}&quot;.
        /// </summary>
        internal static string RemoveHelpFilter {
            get {
                return ResourceManager.GetString("RemoveHelpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing namespace &quot;{0}&quot;.
        /// </summary>
        internal static string RemoveHelpNamespace {
            get {
                return ResourceManager.GetString("RemoveHelpNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing plug-in &quot;{0}&quot; from &quot;{1}&quot;.
        /// </summary>
        internal static string RemoveHelpPlugin {
            get {
                return ResourceManager.GetString("RemoveHelpPlugin", resourceCulture);
            }
        }
    }
}
