using System;
using System.IO;
using System.Xml;
using System.Text;
using System.Collections.Generic;

namespace Sandcastle.References
{
    [Serializable]
    public sealed class ReferenceCommentConfiguration : ReferenceConfiguration
    {
        #region Public Fields

        /// <summary>
        /// Gets the unique name of this configuration.
        /// </summary>
        /// <value>
        /// A string specifying the unique name of this configuration.
        /// </value>
        public const string ConfigurationName =
            "Sandcastle.References.ReferenceCommentConfiguration";

        #endregion

        #region Private Fields

        private bool _fixComments;
        private bool _useNamespaceDoc;

        #endregion

        #region Constructors and Destructor

        /// <overloads>
        /// Initializes a new instance of the <see cref="ReferenceCommentConfiguration"/> class.
        /// </overloads>
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferenceCommentConfiguration"/> class
        /// to the default values.
        /// </summary>
        public ReferenceCommentConfiguration()
            : this(ConfigurationName)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReferenceCommentConfiguration"/> class
        /// with the specified options or category name.
        /// </summary>
        /// <param name="optionsName">
        /// A <see cref="System.String"/> specifying the name of this category of options.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// If the <paramref name="optionsName"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="ArgumentException">
        /// If the <paramref name="optionsName"/> is empty.
        /// </exception>
        private ReferenceCommentConfiguration(string optionsName)
            : base(optionsName)
        {
            _fixComments     = true;
            _useNamespaceDoc = true;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReferenceCommentConfiguration"/> class
        /// with parameters copied from the specified instance of the 
        /// <see cref="ReferenceCommentConfiguration"/> class, a copy constructor.
        /// </summary>
        /// <param name="source">
        /// An instance of the <see cref="ReferenceCommentConfiguration"/> class from which the
        /// initialization parameters or values will be copied.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// If the parameter <paramref name="source"/> is <see langword="null"/>.
        /// </exception>
        public ReferenceCommentConfiguration(ReferenceCommentConfiguration source)
            : base(source)
        {
            _fixComments     = source._fixComments;
            _useNamespaceDoc = source._useNamespaceDoc;
        }

        #endregion

        #region Public Properties

        /// <inheritdoc/>
        public override string Category
        {
            get
            {
                return "ReferenceVisitor";
            }
        }

        /// <summary>
        /// Gets or sets a value specifying whether to fix the comments generated 
        /// by the compiler.
        /// </summary>
        /// <value>
        /// This is <see langword="true"/> when the fixing of the comments is allowed; 
        /// otherwise, it is <see langword="false"/>. The default is <see langword="false"/>.
        /// </value>
        /// <remarks>
        /// Currently only the comments generated by the MC++ or CLR/C++ is fixed.
        /// </remarks>
        public bool FixComments
        {
            get
            {
                return _fixComments;
            }
            set
            {
                _fixComments = value;
            }
        }

        public bool UsesNamespaceDoc
        {
            get
            {
                return _useNamespaceDoc;
            }
            set
            {
                _useNamespaceDoc = value;
            }
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Creates the visitor implementation for this configuration.
        /// </summary>
        /// <returns>
        /// A instance of the reference visitor, <see cref="ReferenceVisitor"/>,
        /// which is used to process this configuration settings during build.
        /// </returns>
        public override ReferenceVisitor CreateVisitor()
        {
            return new ReferenceCommentVisitor(this);
        }

        #endregion

        #region ICloneable Members

        /// <summary>
        /// This creates a new build object that is a deep copy of the current 
        /// instance.
        /// </summary>
        /// <returns>
        /// A new build object that is a deep copy of this instance.
        /// </returns>
        public override BuildConfiguration Clone()
        {
            ReferenceCommentConfiguration options = new ReferenceCommentConfiguration(this);

            return options;
        }

        #endregion
    }
}
